### ISSUE TITLE
dump frequency can cause simulation to run beyond total_time

### ISSUE THREAD

**Issue by peterscherpelz** [ModernElectron/WarpX#168]
If one sets total time to say 1 ns, diag time to 1 ns, but dump frequency to 5, then the simulation will run for 5 ns to reach the first dump before it stops. This isn't a problem in production runs but counterintuitive in testing. Perhaps it should just throw errors if total time < the largest of the diagnostic periods, because I believe the dump gets entered as a diagnostic period in the `mewarpx.utils_store.util.compute_step` function.

**Comment by roelof-groenewald** [comment]
This should be fixed by #167 .
