### ISSUE TITLE
No particles recorded as scraped on embedded boundaries in flux diagnostics

### ISSUE THREAD

**Issue by peterscherpelz** [ModernElectron/WarpX#170]
Some runs were done successfully on version 7.0.0 with the addition of the AMREX checkpoint formatting fix that Andrew implemented - the most recent `psdevel` branch commit as of today.

Failed versions were started on 3/19 from memaster - mewarpx version 7.1.1. Identical template files.

In the more recent ones, no current ever shows up as collected on the embedded boundary, e.g. printout looks like:
```
eb spec1 Current Emitted: X A/cm^2
eb spec1 Current Collected: 0 A/cm^2
eb spec1 Current Net: X A/cm^2
eb spec2 Current Collected: 0 A/cm^2
eb spec3 Current Collected: 0 A/cm^2
```

**Comment by peterscherpelz** [comment]
FYI @KZhu-ME @PhilMiller too. It looks like the particles are still removed from the simulation, but not recorded in flux diagnostics. Likely a change in WarpX, not our stuff? So I bounded the versions/dates above.

**Comment by roelof-groenewald** [comment]
There is an early `return` in the loop over species in `Assembly._read_scraped_particles()` if a given species had zero particles in the scraped particle buffer. This is fixed by `continue`ing the loop rather than `return`ing from the function.
